server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: ${db.console.url}
      settings:
        web-allow-others: true
  datasource:
    url: ${db.url}
    driverClassName: ${db.driver.name}
    username: ${db.user.id}
    password: ${db.user.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


  sql:
    init:
      mode: always

timeZone:
  location:
    asia_seoul: Asia/Seoul

multipart:
  upload:
    path: ${image.upload.path}

oauth2:
  user:
    google:
      client-id: ${Oauth.client-id}
      client-secret: ${Oauth.client-secret}
      redirect-uri: ${Oauth.redirect.url}
      scope:
        - email
        - profile
  provider:
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


jwt:
  token:
    secret-key: ${token.secret.key}
