server:
  port: '8080'
#  ssl:
#    key-store: "classpath:keystore.p12"
#    key-store-type: PKCS12
#    key-store-password: ${ssl.password}
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: ${database.url}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}
  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: never

timeZone:
  location:
    asia_seoul: "Asia/Seoul"

multipart:
  upload:
    path: "/upload/"

jwt:
  token:
    secret-key: ${jwt.secret.key}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace


